### PR TITLE
Adding Edit Account

### PR DESCRIPTION
**Pull request by SpartanFA**

### CODE REVIEW

**Review by ArcFlu — CHANGES_REQUESTED** [review]
FetchEventData has a buggy url.

**Review by EminMammadzada — CHANGES_REQUESTED** [review]
does not look good

**Review by SpartanFA — COMMENTED** [review]
Please look at it again.

**Review by EminMammadzada — APPROVED** [review]

**Review by ArcFlu — APPROVED** [review]
Looks good!

**Pull request merged**
